"use client";

import { useState } from "react";

export default function HomePage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const closeMenu = () => setMenuOpen(false);

  return (
    <>
      <div className="topline"><div className="wrap topline-inner"><span>THE TIMBER GIANTS <i>•</i> SAMREBOI, GHANA</span><a href="https://www.fcsamartex.com/fixtures-results-men" target="_blank" rel="noopener noreferrer">MATCH CENTRE <b>↗</b></a></div></div>
      <header className="header"><div className="wrap nav"><a className="brand" href="#home" aria-label="FC Samartex home"><img src="/assets/crest.png" alt="FC Samartex crest"/><span><strong>FC SAMARTEX</strong><small>ONE CLUB. ONE COMMUNITY.</small></span></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-controls="primary-nav" aria-label={menuOpen ? "Close navigation" : "Open navigation"}><span/><span/></button><nav id="primary-nav" className={menuOpen ? "open" : ""} aria-label="Main navigation"><a href="#news" onClick={closeMenu}>News</a><a href="#match" onClick={closeMenu}>Match Centre</a><a href="#teams" onClick={closeMenu}>Teams</a><a href="#club" onClick={closeMenu}>Our Club</a><a className="nav-cta" href="https://www.fcsamartex.com/jerseys" target="_blank" rel="noopener noreferrer">VISIT THE SHOP <span>↗</span></a></nav></div></header>
      <main id="home">
        <section className="hero"><div className="hero-bg"/><div className="wrap hero-content"><p className="eyebrow"><span/> ROOTED IN SAMREBOI. READY FOR MORE.</p><h1>BUILT FROM<br/>THE <em>FOREST.</em></h1><p className="hero-copy">Pride of the Western Region. The Timber Giants carry Samreboi with them — wherever the game takes us.</p><div className="hero-actions"><a className="button button-green" href="#match">FOLLOW THE ACTION <b>↓</b></a><a className="text-link" href="#club">DISCOVER OUR STORY <span>↗</span></a></div><div className="hero-mark"><img src="/assets/crest.png" alt=""/></div><div className="hero-foot"><span>FC SAMARTEX 1996</span><span>EST. 1995 <i>—</i> SAMREBOI, GHANA</span></div></div><div className="hero-side">WESTERN<br/>REGION<br/><b>GHANA</b></div></section>
        <section className="match-section" id="match"><div className="wrap match-wrap"><div className="section-label"><span className="live-dot"/> NEXT FIXTURE <small>MEN’S FIRST TEAM</small></div><div className="match-card"><div className="match-meta"><span>GHANA PREMIER LEAGUE</span><span>OFFICIAL CLUB FIXTURE LIST</span></div><div className="match-main"><div className="club-side"><img src="/assets/crest.png" alt="FC Samartex crest"/><div><strong>FC SAMARTEX</strong><small>THE TIMBER GIANTS</small></div></div><div className="match-centre"><span className="vs">VS</span><strong>26 <small>SEP</small></strong><span>SATURDAY · 3:00 PM</span></div><div className="club-side away"><div><strong>SWEDRU ALL BLACKS</strong><small>UNITED FC</small></div><div className="away-badge">AB</div></div></div><div className="match-bottom"><span>SWEDRU SPORTS STADIUM</span><a href="https://www.fcsamartex.com/fixtures-results-men" target="_blank" rel="noopener noreferrer">FULL FIXTURES &amp; RESULTS <b>↗</b></a></div></div><div className="match-note">Fixture details shown as published on the club website; check official channels for changes.</div></div></section>
        <section className="news-section section-pad" id="news"><div className="wrap"><div className="section-head"><div><p className="eyebrow dark-eyebrow">FROM THE CLUB</p><h2>THE LATEST <em>WORD.</em></h2></div><a className="under-link" href="https://www.fcsamartex.com/latest-news" target="_blank" rel="noopener noreferrer">ALL CLUB NEWS <span>↗</span></a></div><div className="news-grid"><a className="news-card feature" href="https://www.fcsamartex.com/latest-news" target="_blank" rel="noopener noreferrer"><div className="news-image"><img src="/assets/news-one.jpg" alt="Club news from FC Samartex" loading="lazy"/><span className="image-tag">MEN’S TEAM</span></div><div className="news-copy"><small>OFFICIAL CLUB NEWS</small><h3>Every match. Every moment. Follow the Giants.</h3><p>Match reports, club updates and the stories behind the badge — straight from Samartex.</p><span className="read-link">READ THE LATEST <b>↗</b></span></div></a><a className="news-card" href="https://www.fcsamartex.com/gallery" target="_blank" rel="noopener noreferrer"><div className="news-image"><img src="/assets/news-two.jpg" alt="FC Samartex club photography" loading="lazy"/><span className="image-tag">MATCHDAY</span></div><div className="news-copy"><small>ONE CLUB, EVERY TEAM</small><h3>The moments that bring us together.</h3><span className="read-link">VISIT THE GALLERY <b>↗</b></span></div></a><a className="news-card" href="https://www.fcsamartex.com/latest-videos" target="_blank" rel="noopener noreferrer"><div className="news-image"><img src="/assets/news-three.jpg" alt="Football at FC Samartex" loading="lazy"/><span className="image-tag">WATCH</span></div><div className="news-copy"><small>INSIDE THE CLUB</small><h3>Come closer to the action.</h3><span className="read-link">WATCH CLUB VIDEOS <b>↗</b></span></div></a></div><p className="source-note">For the latest verified headlines, visit the club’s official news page.</p></div></section>
        <section className="teams-section" id="teams"><div className="wrap teams-layout"><div className="teams-intro"><p className="eyebrow">ONE BADGE. EVERY TEAM.</p><h2>THE GIANTS<br/>ARE <em>US.</em></h2><p>Men’s and women’s football. One community behind every side that steps onto the pitch.</p><a className="button button-outline" href="https://www.fcsamartex.com/players-men" target="_blank" rel="noopener noreferrer">EXPLORE THE TEAMS <span>↗</span></a></div><a className="team-tile men" href="https://www.fcsamartex.com/players-men" target="_blank" rel="noopener noreferrer"><img src="/assets/crest.png" alt=""/><span>01 / MEN’S FIRST TEAM</span><strong>THE GIANTS <b>↗</b></strong></a><a className="team-tile women" href="https://www.fcsamartex.com/players-women" target="_blank" rel="noopener noreferrer"><div className="tile-graphic">S</div><span>02 / WOMEN’S TEAM</span><strong>THE FUTURE <b>↗</b></strong></a></div></section>
        <section className="club-section" id="club"><div className="wrap club-layout"><div className="club-stamp"><img src="/assets/crest.png" alt="FC Samartex crest"/></div><div className="club-copy"><p className="eyebrow dark-eyebrow">FROM THE HEART OF THE WEST</p><h2>THIS IS<br/><em>SAMREBOI.</em></h2><p>Our story begins in Samreboi, in Ghana’s Western Region. FC Samartex is more than a football club: it is a source of pride, belonging and possibility for our community.</p><a className="under-link" href="https://www.fcsamartex.com/about-the-club" target="_blank" rel="noopener noreferrer">MORE ABOUT THE CLUB <span>↗</span></a></div><div className="club-stat"><strong>1995</strong><span>THE YEAR OUR<br/>JOURNEY BEGAN</span><small>Club history source: official website</small></div></div></section>
        <section className="closing"><div className="wrap closing-inner"><img src="/assets/crest.png" alt=""/><p>THE FOREST IS OURS.<br/><strong>THE FUTURE IS OURS.</strong></p><a href="https://www.fcsamartex.com" target="_blank" rel="noopener noreferrer">FOLLOW THE CLUB <span>↗</span></a></div></section>
      </main>
      <footer><div className="wrap footer-main"><a className="brand footer-brand" href="#home"><img src="/assets/crest.png" alt=""/><span><strong>FC SAMARTEX 1996</strong><small>THE TIMBER GIANTS</small></span></a><p>SAMREBOI · WESTERN REGION · GHANA</p><div className="footer-links"><a href="https://www.fcsamartex.com/contact-us" target="_blank" rel="noopener noreferrer">CONTACT</a><a href="https://www.fcsamartex.com/gallery" target="_blank" rel="noopener noreferrer">GALLERY</a><a href="https://www.fcsamartex.com" target="_blank" rel="noopener noreferrer">OFFICIAL SITE ↗</a></div></div><div className="wrap footer-bottom"><span>© FC SAMARTEX 1996</span><span>ONE CLUB. ONE COMMUNITY.</span></div><div className="wrap footer-credit"><span>Built with love by</span><a href="https://webarastudio.com" target="_blank" rel="noopener noreferrer"><img src="/assets/webara-icon.png" alt="" width={22} height={22} /><span>webarastudio.com</span></a></div></footer>
    </>
  );
}
